pytrip/pytripgui

pytripgui/guiutil.py
pytripgui/panels/plotpanel.py

guiutil class import

---

README.rst
docs/technical.rst

Removing unnecessary files

---

README.rst
requirements.txt
setup.cfg
setup.py
tests/requirements-test.txt

proper setup.py description

---

pytripgui/main.py
setup.py

fixed imports

---

pytripgui/__init__.py
pytripgui/closeobj.py
pytripgui/data.py
pytripgui/dialogs/__init__.py
pytripgui/dialogs/createcubedialog.py
pytripgui/dialogs/createstructuredialog.py
pytripgui/dialogs/dosedialog.py
pytripgui/dialogs/fielddialog.py
pytripgui/dialogs/plandialog.py
pytripgui/dialogs/progressdialog.py
pytripgui/dialogs/tripexportcubedialog.py
pytripgui/dialogs/tripexportdialog.py
pytripgui/dialogs/triplogdialog.py
pytripgui/dialogs/tripvoidialog.py
pytripgui/dialogs/voidialog.py
pytripgui/dose.py
pytripgui/guihelper.py
pytripgui/leftmenu.py
pytripgui/main.py
pytripgui/panels/2dplot.py
pytripgui/panels/__init__.py
pytripgui/panels/dvh.py
pytripgui/panels/multidimplot.py
pytripgui/panels/plotpanel.py
pytripgui/plugin.py
pytripgui/rbehandler.py
pytripgui/settings.py
pytripgui/test.py
pytripgui/tripexecparser.py
pytripgui/util.py

Remove references to libdedx.

---

pytripgui/main.py

wildcard problems with wxwidgets 3.0

---

appveyor.yml
pytripgui/data.py
tests/requirements-test.txt

VdxCube API updated

---

appveyor.yml
pytripgui/guiutil.py

Fix slice number starting in 0 in gui. 

---

pytripgui/guiutil.py
pytripgui/main.py
pytripgui/panels/plotpanel.py
pytripgui/res/gui.fbp
pytripgui/res/main.xrc

Closes #34 
Closes #40 
Closes #53

Make CT HU colourbar behave properly

---

appveyor.yml

automatic deploying of installer files to github release page

---

appveyor.yml

path to artifact adjusted

---

appveyor.yml

artifact names used

---

pytripgui/guiutil.py

Closes #73, but requires this merge on pytrip: https://github.com/pytrip/pytrip/pull/270

Fix slice position issue and more

---

pytripgui/guiutil.py

Consistent offset behaviour

---

pytripgui/guiutil.py
pytripgui/panels/plotpanel.py

fix plane switching, correct spelling mistake

---

pytripgui/data.py
pytripgui/dialogs/tripvoidialog.py
pytripgui/leftmenu.py
pytripgui/panels/dvh.py
pytripgui/panels/plotpanel.py

some minor code cleaning
fixes #89

toogle -> toggle typo fixed

---

pytripgui/guiutil.py

Add orientation markers #91

---

pytripgui/guiutil.py

Add some function which may draw a point #63

---

pytripgui/data.py
pytripgui/dialogs/tripexportcubedialog.py
pytripgui/leftmenu.py
pytripgui/main.py

improved loading of Voxel plans

---

pytripgui/guiutil.py
pytripgui/main.py

Fix open contour issue

---

.gitattributes
pytripgui/dialogs/createcubedialog.py
pytripgui/res/main.xrc
pytripgui/res/panels.xrc

Fix #59, broken .xrc file and data
Fix #33, plans could not be edited.

Fix cryptic error when creating new cubes.

---

pytripgui/main.py
pytripgui/res/panels.xrc

Fix more GUI issues #100

---

pytripgui/guiutil.py

minor code refactoring
Closes #96

included offsets when displaying contours in sagittal and coronal planes

---

pytripgui/data.py
pytripgui/dialogs/triplogdialog.py
pytripgui/util.py

proper TripLog output

---

pytripgui/main.py
pytripgui/res/gui.fbp
pytripgui/res/main.xrc

Add Python console,

---

pytripgui/dialogs/tripconfigdialog.py
pytripgui/leftmenu.py
pytripgui/res/panels.fbp
pytripgui/res/panels.xrc

add missing te.trip98_bin_path

---

pytripgui/guiutil.py
pytripgui/leftmenu.py
pytripgui/panels/plotpanel.py

Closes #140 
However, viewing Dose and LET is broken handled in a bad way. 
Need a better solution for this.

Fix LETCubes load and display

---

appveyor.yml
makeui.bat
makeui.sh
pytripgui/view/gen/__init__.py

pip 10.x fix

---

pytripgui/controller/main_cont.py
pytripgui/controller/settings.py
pytripgui/view/dialogs.py
pytripgui/view/main_window.ui

Fixes #62 , conversion in both directions now possible (many errors still on pytrip side)

Add export DICOM and export VOXELPLAN 

---

pytripgui/controller/plot_cont.py
pytripgui/controller/tree_cont.py
pytripgui/controller/vdx.py

closes #178 
Requires PyTRiP PR https://github.com/pytrip/pytrip/pull/466

Fix POIs and contours #178.

---

pytripgui/controller/main_cont.py
pytripgui/controller/tree_cont.py

fix error when no VDX file available.

---

.gitignore
README.rst
docs/technical.rst
pytripgui/controller/field_cont.py
pytripgui/controller/main_cont.py
pytripgui/controller/plan_cont.py
pytripgui/controller/tree_cont.py
pytripgui/controller/tree_menu_cont.py

This MR:
- fixes compability with recent PyTRiP98
- add more documentation 
- update README.md
- adds initial work for the field dialog

Adapt to new PyTRiP, inital field dialog work

---

pytripgui/main.py

A bit safer start in case no arguments given.

---

pytripgui/controller/field_cont.py
pytripgui/controller/plan_cont.py
pytripgui/controller/tree_menu_cont.py

Adding feature: execute plan from GUI
bugfix: all components required by plan executor

Adding option 'execute plan' to context menu

---

pytripgui/controller/main_cont.py
pytripgui/controller/tree_menu_cont.py
pytripgui/field_vc/__init__.py
pytripgui/field_vc/field_cont.py
pytripgui/field_vc/field_view.py
pytripgui/plan_vc/__init__.py
pytripgui/plan_vc/plan_cont.py
pytripgui/plan_vc/plan_view.py
pytripgui/view/plan.ui

I have to add a little bit code more to make it work.

initial work to make 'plan' code more MVC

---

pytripgui/__init__.py
pytripgui/version.py
setup.py

improved versioning for developer version

---

pytripgui/view/field.ui

fix width of FWHM in field view

---

pytripgui/config_vc/__init__.py
pytripgui/config_vc/config_cont.py
pytripgui/config_vc/config_view.py
pytripgui/controller/main_cont.py
pytripgui/model/config_model.py
pytripgui/model/main_model.py
pytripgui/view/trip_config.ui

Adding trip config to GUI

---

pytripgui/controller/dos.py
pytripgui/controller/main_cont.py
pytripgui/controller/plot_cont.py
pytripgui/controller/tree_cont.py
pytripgui/controller/tree_menu_cont.py
pytripgui/model/dos_container.py
pytripgui/model/main_model.py

display dos after execute: initial commit

---

pytripgui/main_window_qt_vc/main_window_cont.py

246 broken master

---

pytripgui/main.py
pytripgui/main_window_qt_vc/__init__.py
setup.py

modified setup.py:
- fixed python version to a correct one
- added pyqt5 as require package during installation
Fixes #249

missing module __init__ file added,

---

requirements.txt
setup.py

unneeded packages removed from requirement list

---

.gitignore
MANIFEST.in
appveyor.yml
main.spec
pytripgui/__init__.py
setup.py
tox.ini

Improved versioning

---

pytripgui/kernel_vc/kernel_cont.py
pytripgui/plan_executor/executor.py
pytripgui/plan_executor/simulation_results.py
pytripgui/plan_vc/plan_cont.py
pytripgui/treewidget_vc/treewidget_cont.py
pytripgui/viewcanvas_vc/viewcanvas_cont.py
requirements.txt
setup.py

Adopt to new pytrip98 API

---

pytripgui/view/main_window.ui

Disable unimplemented features

---

tests/requirements-test.txt

it seems that 1.x release of pyvirtualdisplay creates problems on travis

---

pytripgui/tree_vc/TreeItems.py

Naming items in tree, counting fields, add field number to name

---

pytripgui/main_window_qt_vc/app_callbacks.py
pytripgui/main_window_qt_vc/main_window_cont.py
pytripgui/model/plot_model.py
pytripgui/plan_executor/executor.py
pytripgui/plan_executor/simulation_results.py
pytripgui/view/viewcanvas.ui
pytripgui/viewcanvas_vc/viewcanvas_cont.py
pytripgui/viewcanvas_vc/viewcanvas_view.py
tests/requirements-test.txt

add comboBox, radio buttons, slider.

---

pytripgui/tree_vc/TreeController.py
pytripgui/tree_vc/TreeModel.py
pytripgui/tree_vc/TreeView.py

Automatically highlight newly added element

---

pytripgui/app_logic/app_callbacks.py
pytripgui/main_window_qt_vc/main_window_cont.py

"Create field" button works also when FieldItem is selected in tree

---

pytripgui/app_logic/app_callbacks.py
pytripgui/tree_vc/TreeItems.py

clearing code structure, remove all fields before appending

---

pytripgui/app_logic/app_callbacks.py
pytripgui/app_logic/viewcanvas.py
pytripgui/main_window_qt_vc/main_window_cont.py
pytripgui/main_window_qt_vc/main_window_view.py
pytripgui/model/main_model.py
pytripgui/view/main_window.ui

don't display unnecessary views

---

pytripgui/field_vc/field_cont.py
pytripgui/field_vc/field_view.py
pytripgui/tree_vc/TreeItems.py
pytripgui/view/field.ui

kernel can be selected only on plan level

---

.travis.yml
appveyor.yml
requirements.txt
setup.py

Truing to fix dependency on pyqt5, see #204

Fixing pyqt5 dependency

---

pytripgui/model/dos.py
pytripgui/model/plot_model.py
pytripgui/viewcanvas_vc/viewcanvas_view.py

dose overlay display improved

---

pytripgui/app_logic/app_callbacks.py
pytripgui/main_window_qt_vc/main_window_cont.py
pytripgui/main_window_qt_vc/main_window_view.py
pytripgui/plan_executor/patient_model.py
pytripgui/view/add_patient.ui
pytripgui/view/main_window.ui
pytripgui/view/qt_gui.py

Opening dicom works

---

pytripgui/app_logic/app_callbacks.py
pytripgui/messages.py
pytripgui/plan_vc/plan_cont.py
pytripgui/plan_vc/plan_view.py
pytripgui/view/plan.ui

target as list with radio-buttons

---

pytripgui/main.py
pytripgui/main_window_qt_vc/main_window_cont.py

Unimplemented function cause error during GUI loading

---

pytripgui/viewcanvas_vc/objects/vdx.py

Fix: Non-iterable value used in an iterating context

---

pytripgui/view/qt_view_adapter.py

Fix: Non-callable object is being called

---

pytripgui/app_logic/app_callbacks.py
pytripgui/app_logic/patient_tree.py
pytripgui/main_window_qt_vc/main_window_cont.py
pytripgui/main_window_qt_vc/main_window_view.py
pytripgui/view/main_window.ui
tests/test_patient_tree.py

View -> patient tree
closes #367

Add possibility to reopen patient treeView

---

pytripgui/viewcanvas_vc/plot_model.py
pytripgui/viewcanvas_vc/viewcanvas_view.py

I added quite simple coords` info. In upper right corner there is a 3D wireframe cube that represents our patient and there are three planes in it, each painted with different color - selected plane is opaque, others are semi-transparent. 
Works better on fullscreen :)
closes #316

Coordinates` information

---

.github/workflows/test.yml
appveyor.yml

Fix for package upload

---

appveyor.yml
main.spec

Turning off UPX, because it can generate false positives on antiviruses

turn off UPX

---

pytripgui/main.py

The MainWindowController object was getting garbage collected before app execution, causing the callback it contains to be lost.
Closes #431

About button fix

---

pytripgui/canvas_vc/plotter/coordinate_info.py

Coordinate info enhancements

---

pytripgui/canvas_vc/plotter/managers/voi_manager.py
requirements.txt
setup.py

If 
- pytrip/pytrip#606 is merged and new version is deployedthen this can be merged
closes 
- #448

VOI colors matching pytrip

---

pytripgui/canvas_vc/canvas_controller.py
pytripgui/view/qt_view_adapter.py

VOI list item checking fix (#453)

---

pytripgui/app_logic/app_callbacks.py
pytripgui/app_logic/viewcanvas.py
pytripgui/canvas_vc/canvas_controller.py
pytripgui/canvas_vc/gui_state.py
pytripgui/view/qt_view_adapter.py

Fixed saving checked VOI when changing patients by:
- adding new object that holds gui state
- adding new method in ListWidget, which checks passed items
- changing set_patient method to properly use new state object
closes #438 
- #438

Saving checked VOIs (438)

---

.deepsource.toml

Remove yapf from .deepsource.toml

---

pytripgui/app_logic/app_callbacks.py
pytripgui/canvas_vc/objects/ctx.py
pytripgui/controller/dvh.py
pytripgui/controller/lvh.py
pytripgui/main_window_qt_vc/main_window_view.py

closes #387 
closes #388
closes #390 
- #387 
- #388
- #390

Apply deepsource suggestions

---

pytripgui/messages.py
setup.py

fixing contributor list

---

AUTHORS.rst
docs/technical.rst

fixed typos in author names

---

setup.py

added missing OSs

---

pytripgui/canvas_vc/plotter/bars/bar_base.py
pytripgui/canvas_vc/plotter/managers/voi_manager.py
pytripgui/main.py

muted pyqt5 and matplotlib logging

---

.github/workflows/test.yml
setup.py

properly excluding tests directory from packaging

---

pytripgui/canvas_vc/plotter/images/dose_image.py

fix dose background arftifacts

---

pytripgui/app_logic/viewcanvas.py
pytripgui/canvas_vc/canvas_controller.py

Missing docs in set_patient

---

.gitignore

improved .gitgnore by adding pycharm settings

---

pytripgui/app_logic/app_callbacks.py
pytripgui/app_logic/patient_tree.py
pytripgui/main_window_qt_vc/main_window_cont.py
pytripgui/main_window_qt_vc/main_window_view.py
pytripgui/tree_vc/tree_controller.py
pytripgui/tree_vc/tree_view.py
pytripgui/view/main_window.ui

DICOM and Voxelplan imports for Dose implemented.
closes #487

Import dose cube

---

pytripgui/canvas_vc/canvas_controller.py
pytripgui/canvas_vc/objects/ctx.py
pytripgui/canvas_vc/objects/data_base.py
pytripgui/canvas_vc/objects/dos.py
pytripgui/canvas_vc/objects/let.py
pytripgui/canvas_vc/plotter/images/ctx_image.py
pytripgui/canvas_vc/plotter/images/dose_image.py
pytripgui/canvas_vc/plotter/images/let_image.py
pytripgui/canvas_vc/plotter/images/patient_image_base.py
pytripgui/canvas_vc/plotter/managers/plotting_manager.py
pytripgui/canvas_vc/plotter/managers/voi_manager.py
pytripgui/canvas_vc/projection_selector.py

Retrived code from old branch, but it does not work properly, as contours are plotted outside the image, further investigation is needed
closes #458 
closes #540 
- #458 
- #540

Add extent and aspect to images

---

pytripgui/add_vois_vc/add_single_voi_vc/add_single_voi_cont.py
pytripgui/add_vois_vc/add_vois_cont.py
pytripgui/add_vois_vc/voi_widget.py
pytripgui/add_vois_vc/widgets/cylindrical_voi.ui
pytripgui/empty_patient_vc/empty_patient_cont.py
pytripgui/empty_patient_vc/empty_patient_view.py
pytripgui/view/add_single_voi.ui
pytripgui/view/empty_patient.ui

Reliant on https://github.com/pytrip/pytrip/pull/637
Offsets in UI:

Added offsets to empty patient and an ability to add cylindrical VOIs

---

pytripgui/canvas_vc/canvas_controller.py
pytripgui/view/qt_view_adapter.py

Closes #547 
- #547 
edit: changed size of icons to match checkbox size:

Add color icons to VOI list

---

pytripgui/app_logic/app_callbacks.py
pytripgui/app_logic/patient_tree.py
pytripgui/app_logic/viewcanvas.py
pytripgui/canvas_vc/canvas_controller.py
pytripgui/canvas_vc/canvas_view.py
pytripgui/canvas_vc/plotter/mpl_plotter.py
pytripgui/main_window_qt_vc/main_window_cont.py
pytripgui/view/data_sample.py
pytripgui/view/data_sample.ui
pytripgui/view/main_view.py
pytripgui/view/main_window.ui
pytripgui/view/viewcanvas.ui
tests/test_patient_tree.py

Moved VOI list, added mouseover info with position and dose/let info, cleaned up some code. Some TODOs are still left.

Mouseover info and UI changes

---

.github/workflows/sphinx.yml
docs/index.rst

changed deploy path and added technical to table of content

sphinx fix

---

pytripgui/app_logic/app_callbacks.py
pytripgui/canvas_vc/plotter/managers/voi_manager.py
pytripgui/contouring_vc/contouring_controller.py
pytripgui/contouring_vc/contouring_view.py
pytripgui/loading_file_vc/loading_file_controller.py
pytripgui/loading_file_vc/loading_file_view.py
pytripgui/view/contouring_dialog.ui
pytripgui/view/qt_gui.py
requirements.txt
setup.py

merge after pytrip/pytrip#663 is merged
- pytrip/pytrip#663
closes #555 
- #555

Concave support v2

---

pytripgui/app_logic/app_callbacks.py
pytripgui/app_logic/gui_executor.py
pytripgui/canvas_vc/canvas_controller.py
pytripgui/canvas_vc/objects/ctx.py
pytripgui/canvas_vc/objects/data_base.py
pytripgui/canvas_vc/objects/dos.py
pytripgui/canvas_vc/objects/let.py
pytripgui/canvas_vc/objects/vdx.py
pytripgui/canvas_vc/plot_model.py
pytripgui/canvas_vc/plotter/images/patient_image_base.py
pytripgui/canvas_vc/plotter/managers/plotting_manager.py
pytripgui/plan_executor/executor.py
pytripgui/plan_executor/simulation_results.py
pytripgui/plan_vc/plan_view.py
pytripgui/view/plot_volhist.py

to test it, this PR will be useful: pytrip/pytrip#667

multiple dose and let types in one simulation

---

pytripgui/app_logic/app_callbacks.py
pytripgui/plan_executor/simulation_results.py

Private method that does not exist now was used and caused errors

fix dose import error

---

README.rst
docs/readme.rst
docs/technical.rst
docs/user_guide.rst

Hotfix for the 404 error from developer documentation link in README.

Split readme files and fix URLs

---

pytripgui/contouring_vc/contouring_controller.py
pytripgui/contouring_vc/contouring_view.py

Fix typo and change wording to reflect operation speed-up from pytrip/pytrip#672

Contouring popup text change
